### ISSUE TITLE
Wrong code in Prefix getter

### ISSUE THREAD

**Issue by martin-honnen** [AngleSharp/AngleSharp.XPath#28]
The line https://github.com/AngleSharp/AngleSharp.XPath/blob/master/src/AngleSharp.XPath/HtmlDocumentNavigator.cs#L80
has the code
```
        public override string Prefix =>
            _attrIndex != 1
                ? NameTable.GetOrAdd(CurrentElement.Attributes[_attrIndex].Prefix ?? string.Empty)
                : NameTable.GetOrAdd(CurrentElement?.Prefix ?? string.Empty);

```
The other getters compare `_attrIndex != -1`, I think the getter above for `Prefix` also needs the compare to `-1`, otherwise the attempt to look up a prefix throws a `NullReferenceException`

```
System.NullReferenceException
  HResult=0x80004003
  Nachricht = Object reference not set to an instance of an object.
  Quelle = AngleSharp.XPath
  Stapelüberwachung:
   at AngleSharp.XPath.HtmlDocumentNavigator.get_Prefix()
```

**Comment by martin-honnen** [comment]
@denis-ivanov , is that code ` _attrIndex != 1` in  `public override string Prefix =>` not fixable by using `_attrIndex != -1` instead?

**Comment by denis-ivanov** [comment]
Hello, @martin-honnen !
Field `_attrIndex` was removed in `2.0.0-alpha-1`.
