### ISSUE TITLE
Will 2.0 only support .NET (Core) and not .NET framework?

### ISSUE THREAD

**Issue by martin-honnen** [AngleSharp/AngleSharp.XPath#32]
@denis-ivanov , in https://github.com/AngleSharp/AngleSharp.XPath/commit/dfd9d33a7eb0201de6a7229ee13a4adcb37f926c#diff-615740254f47d7a152d8b39cff4d7b49d0aa3db2821f2f67ebe6f13ad0ab45beR10 it seems the target framework was changed from .NET Standard 2.0 to .NET Core 5. That way AngleSharp.XPath 2.0 would no longer be compatible and usable from any .NET framework app. Is that intended? Other AngleSharp packages seem to try to maintain .NET Standard 2.0 as the base to allow use from both .NET framework as well as .NET Core code.

**Comment by denis-ivanov** [comment]
Fixed #33.
