### ISSUE TITLE
v2.0.0 regression with XPaths ending on `/@attr`

### ISSUE THREAD

**Issue by JustArchi** [AngleSharp/AngleSharp.XPath#36]
Hello.

Consider this example HTML that I've extracted from one of the websites I'm using:

```html
<html>
<body>
	<table class= "accountTable" >
			<thead><tr>
				<th>  </th>
				<th> DEVICE NAME </th>
				<th> Sharing Status </th>
				<th> LIBRARY LAST ACCESSED </th>
				<th> BY STEAM USER </th>
			</tr>
			</thead>
			<tbody>

			
					<tr data-panel="{&quot;maintainY&quot;:true,&quot;flow-children&quot;:&quot;row&quot;}">
						<td> 1 </td>
						<td> redacted </td>
						<td>
															Authorized (
								<a href="javascript:DeauthorizeDevice( 'redacted', 'redacted' );">Revoke</a> )
													</td>
						<td> redacted </td>
						<td> <a href="https://steamcommunity.com/id/redacted/" data-miniprofile="redacted-test">redacted</a> </td>
					</tr>
							</tbody>
		</table>


		<br><br>
		You can allow up to 5 accounts to use your game library on any of your authorized computers.		<br><br>

		<table class= "accountTable" >
			<thead><tr>
				<th>  </th>
				<th> User Name </th>
				<th> Sharing Status </th>
				<th> Time added </th>
			</tr>
			</thead>

			<tbody>
			
					<tr data-panel="{&quot;maintainY&quot;:true,&quot;flow-children&quot;:&quot;row&quot;}">
						<td> 1 </td>
						<td> <a href="https://steamcommunity.com/id/redacted/" data-miniprofile="redacted-test">redacted</a> </td>
						<td>
													Authorized (
							<a href="javascript:DeauthorizeBorrower( 'redacted' );">Revoke</a> )
												</td>
						<td> redacted </td>
					</tr>
							</tbody>
		</table>
</body>
</html>
```

Until now with AngleSharp.XPath version `1.1.7`, I've been using the following xpath expression which worked fine:

```
(//table[@class='accountTable'])[2]//a/@data-miniprofile
```

The objective of the above is to extract all `a` links containing `data-miniprofile` attribute, but only from second `accountTable`.

Unfortunately, the same xpath in version `2.0.0` doesn't return any rows. It worked fine as of version `1.1.7`.

![obraz](https://user-images.githubusercontent.com/1069029/172023032-8d8cbc32-61c4-49ca-a779-3abe2d46b946.png)

I consider this being a regression. If this is planned, may I know what is the recommended way to update in regards to match previous use case?

Thank you in advance for your time.

**Comment by JustArchi** [comment]
@denis-ivanov would you be so kind to look into it? I'd appreciate it a lot, as I consider it pretty severe regression and had to pin my apps to version `1.x` until it's resolved, as it stands right now version 2.0 is pretty broken for me in this regard and entirely unusable. Thank you in advance.

**Comment by denis-ivanov** [comment]
https://github.com/AngleSharp/AngleSharp.XPath/releases/tag/v2.0.1
https://www.nuget.org/packages/AngleSharp.XPath/2.0.1

**Comment by JustArchi** [comment]
It seems to work properly at first, thanks a lot for the fix! :sunglasses:
