### ISSUE TITLE
BUG: SelectSingleNode with search by attribute predicate only works if searched attribute is the first

### ISSUE THREAD

**Issue by fedesasso** [AngleSharp/AngleSharp.XPath#37]
Searching for an element by attribute name only works (apparently) if such attribute is the first.
A unit test is worth a thousand words:

        [Test]
        public void SelectSingleNodeTest_AttributesOrder()
        {
            // Arrange
            const string html =
            @"<body>
				<div id='div1'>First</div>
				<div id='div2' class='mydiv'>Second</div>
				<div class='mydiv' id='div3'>Third</div>
			</body>";
            var parser = new HtmlParser();
            var document = parser.ParseDocument(html);

            // Act
            var div1 = document.DocumentElement.SelectSingleNode("//div[@id='div1']");
            var div2 = document.DocumentElement.SelectSingleNode("//div[@id='div2']");
            var div3 = document.DocumentElement.SelectSingleNode("//div[@id='div3']");

            // Assert
            Assert.That(div1, Is.Not.Null);
            Assert.That(div2, Is.Not.Null);
            Assert.That(div3, Is.Not.Null); // currently fails
        }

In the unit test div2 and div3 sport an additional class attribute. When the class attribute is specified before the id attribute, the search fails.

**Comment by denis-ivanov** [comment]
https://github.com/AngleSharp/AngleSharp.XPath/releases/tag/v2.0.1
https://www.nuget.org/packages/AngleSharp.XPath/2.0.1

**Comment by fedesasso** [comment]
Thank you for the prompt fix!
I suggest deleting from the unit test the last comment (" // currently fails"), no longer true :)
