### ISSUE TITLE
Change default branch

### ISSUE THREAD

**Issue by denis-ivanov** [AngleSharp/AngleSharp.XPath#39]
Hey, @FlorianRappl !
I wrote you to Skype, but you did not answer me. Please, delete devel branch and make master to default branch.
Thanks!

**Comment by FlorianRappl** [comment]
OK so you don't want a preview branch? You want to release directly with no branch to automatically build and release a preview version?

**Comment by denis-ivanov** [comment]
Thanks, I did these changes
