### ISSUE TITLE
Interested in placing this repo in the AngleSharp organization?

### ISSUE THREAD

**Issue by FlorianRappl** [AngleSharp/AngleSharp.XPath#4]
Hi Denis - great project. Since AngleSharp v0.10 is around the corner I would love to keep it compatible. Also, this project fills a gap in AngleSharp so I was thinking about "making it official", i.e., mentioning it in the docs, on the webpage etc.

If you are interested we can discuss details. Long story short would be that you can keep publishing it under your NuGet / name, but the repo would be at the AngleSharp organization (with you having all admin rights for the repo). We could give it some more infrastructure (e.g., fill the readme, provide some CLA, refer to the core, ...).

What are your thoughts on the topic?

**Comment by denis-ivanov** [comment]
Good day!
I think it great idea. Let's discuss details.

**Comment by FlorianRappl** [comment]
Cool, thanks for replying @denis-ivanov !

Yeah the two options I see for the repository:

1. Leave the main repo here, have a fork at the AngleSharp organization. Not much changes, but the (main) repo is still in your name.
2. Move the repo (via GitHub settings) to the AngleSharp organization. You can / will create your own fork in your name (this is what I did to the original AngleSharp repo).

Both ways have pros and cons. I would suggest to go via option 2, but option 1 would be no problem as well. Either way from NuGet's perspective nothing changes. Also the already set up CI/CD would not be touched (besides granting Travis access to the new name in case of option 2).

We can also continue the discussion in, e.g., Skype - my name there is "florian.rappl". Thanks!

**Comment by denis-ivanov** [comment]
> You don’t have the permission to create repositories on AngleSharp

My skype: <DELETED>
