### ISSUE TITLE
Regression: `2.0` now returns `Attr` nodes instead of their parents on xpath ending with `/@attr`

### ISSUE THREAD

**Issue by JustArchi** [AngleSharp/AngleSharp.XPath#40]
Hey.

I've already reported this issue as #36 and thought it's fixed with 2.0.1, but unfortunately, I was testing against yet another problem, which was #37. The original #36 issue is not fixed and is still reproducible with version `2.0.1`.

Original bug report below:

---

Consider this example HTML that I've extracted from one of the websites I'm using:

```html
<html>
<body>
	<table class= "accountTable" >
			<thead><tr>
				<th>  </th>
				<th> DEVICE NAME </th>
				<th> Sharing Status </th>
				<th> LIBRARY LAST ACCESSED </th>
				<th> BY STEAM USER </th>
			</tr>
			</thead>
			<tbody>

			
					<tr data-panel="{&quot;maintainY&quot;:true,&quot;flow-children&quot;:&quot;row&quot;}">
						<td> 1 </td>
						<td> redacted </td>
						<td>
															Authorized (
								<a href="javascript:DeauthorizeDevice( 'redacted', 'redacted' );">Revoke</a> )
													</td>
						<td> redacted </td>
						<td> <a href="https://steamcommunity.com/id/redacted/" data-miniprofile="redacted-test">redacted</a> </td>
					</tr>
							</tbody>
		</table>


		<br><br>
		You can allow up to 5 accounts to use your game library on any of your authorized computers.		<br><br>

		<table class= "accountTable" >
			<thead><tr>
				<th>  </th>
				<th> User Name </th>
				<th> Sharing Status </th>
				<th> Time added </th>
			</tr>
			</thead>

			<tbody>
			
					<tr data-panel="{&quot;maintainY&quot;:true,&quot;flow-children&quot;:&quot;row&quot;}">
						<td> 1 </td>
						<td> <a href="https://steamcommunity.com/id/redacted/" data-miniprofile="redacted-test">redacted</a> </td>
						<td>
													Authorized (
							<a href="javascript:DeauthorizeBorrower( 'redacted' );">Revoke</a> )
												</td>
						<td> redacted </td>
					</tr>
							</tbody>
		</table>
</body>
</html>
```

Until now with AngleSharp.XPath version `1.1.7`, I've been using the following xpath expression which worked fine:

```
(//table[@class='accountTable'])[2]//a/@data-miniprofile
```

The objective of the above is to extract all `a` links containing `data-miniprofile` attribute, but only from second `accountTable`.

Unfortunately, the same xpath in version `2.0.0` or `2.0.1` doesn't return any rows. It worked fine as of version `1.1.7`.

![obraz](https://user-images.githubusercontent.com/1069029/172023032-8d8cbc32-61c4-49ca-a779-3abe2d46b946.png)

I consider this being a regression. If this is planned, may I know what is the recommended way to update in regards to match previous use case?

Thank you in advance for your time.

---

/cc @denis-ivanov

**Comment by denis-ivanov** [comment]
@JustArchi , https://github.com/AngleSharp/AngleSharp.XPath/pull/41

**Comment by JustArchi** [comment]
@denis-ivanov Sorry for misunderstanding, I dug deeper. I'll try to explain in detail now.

Initial problem was indeed related to #37. The current one is that response type has changed.

I've checked on another piece of code I have to ensure this is not a coincidence. In this case I have very similar xpath that also ends on `/@attr`:

```
//div[@id='memberList']/div[starts-with(@class, 'member_block')]/@data-miniprofile
```

This is from old `1.1.7` version:

![obraz](https://user-images.githubusercontent.com/1069029/183246781-42cc8224-0e17-4034-996a-135fb8c2d96b.png)

As you can see, `AngleSharp.XPath` returns list of `HtmlDivElement` objects, each having `Attribtues` which contain `Attr` objects. This matches behaviour of for example `HtmlAgilityPack` and was the original code I've migrated over to `AngleSharp.XPath`.

---

With version `2.0.1`, after #37 being fixed, the equal amount of nodes are returned, but they're now of `Attr` type:

![obraz](https://user-images.githubusercontent.com/1069029/183246900-29ccb23d-1cab-413f-b63d-9cee8bae7e1f.png)

This is a breaking change (regression), because previously I had `HtmlDivElement` objects on which I could call `GetAttribute("attr-name")` and also had access to other data (for example, other attributes than in the xpath query). Right now I have access only to the resulting `Attr` without original node.

I've sent PR to your `issue-40` branch to reproduce the issue. You can verify that it passes on old version of `1.1.7`: https://github.com/AngleSharp/AngleSharp.XPath/pull/42

Logically this change makes sense actually, but it's not compatible with how it worked previously in `AngleSharp.XPath`, but also `HtmlAgilityPack` and probably other xpath solutions. It's definitely a breaking change, the question is if planned or not, I believe it's not planned considering xpath definition, but if I'm wrong, you should probably make important note about it somewhere, as all calls ending on `/@attr` are now working differently.

I'm deeply sorry for misunderstanding and mixing things up. Thank you for your patience.

**Comment by denis-ivanov** [comment]
@JustArchi, current behavior is correct. 1.1.7 - did not support attributes selection, because inside AngleSharp `IAttr` interface did not implement `INode` interface. Since it started to implement it, I updated AngleSharp and **major version**.
If you want old behavior, you have to use `1.1.7`, in other case just find all xpath expressions with attributes and add `/parent::*`.

You can also check browsers behavior (in my case it is MS Edge):
```
$x("(//table[@class='accountTable'])[2]//a/@data-miniprofile")
[data-miniprofile]
```

**Comment by JustArchi** [comment]
Thanks, if this behaviour is intended then I don't have any problem with it and will just adapt the usage. I just wanted to be sure, since I don't want to rewrite a lot of code paths only to revert it later on.

Thanks for your patience and work in regards to this project, I appreciate it, have a nice day! :+1:
