### ISSUE TITLE
Problem with namespaces

### ISSUE THREAD

**Issue by Morhpeuss** [AngleSharp/AngleSharp.XPath#43]
Hi,

I have this XML (XHTML) "<div class=\"hidden\"><ac:structured-macro ac:name=\"section\">   <ac:parameter ac:name=\"border\">true</ac:parameter>  <ac:rich-text-body>    <ac:structured-macro ac:name=\"column\">      <ac:parameter ac:name=\"width\">100px</ac:parameter>      <ac:rich-text-body>        <p>This is the content of <strong>column 1</strong>.</p>      </ac:rich-text-body>    </ac:structured-macro>    <ac:structured-macro ac:name=\"column\">      <ac:rich-text-body>        <p>This is the content of <strong>column 2</strong>.</p>      </ac:rich-text-body>    </ac:structured-macro>  </ac:rich-text-body></ac:structured-macro></div>".

I have a problem selecting all nodes "ac:structured-macro" in the document.

My code:

       ' var contextA = BrowsingContext.New(Configuration.Default.WithXml().WithXPath());

            var parser = new XmlParser(new XmlParserOptions
            {
                IsSuppressingErrors = true
            }, contextA);
            var xmlDoc = parser.ParseDocument(xml);
            XmlReaderSettings settings = new XmlReaderSettings
            {
                NameTable = new NameTable()
            };

            XmlNamespaceManager xmlns = new XmlNamespaceManager(settings.NameTable);
            xmlns.AddNamespace("ac", "http://atlassian.com/content");'

I have tried the following:

xmlDoc.DocumentElement.SelectNodes("//ac|structured-macro") - returns only first element
xmlDoc.DocumentElement.SelectNodes(".//ac|structured-macro") - returns only first element
xmlDoc.DocumentElement.SelectNodes(".//ac|structured-macro", xmlns, false) - returns only first element

xmlDoc.DocumentElement.SelectNodes(".//ac:structured-macro", xmlns, false) - **returns zero elements**

xmlDoc.DocumentElement.SelectNodes("//structured-macro") - **this only returns 3 elements**

Any suggestion on how to work with namespaces and get all nodes?

Thanks.

Josef

**Comment by denis-ivanov** [comment]
@Morhpeuss, please format your XHTML with tags.

**Comment by Morhpeuss** [comment]
@denis-ivanov what do you mean with "format with tags"? Send me please an example.

**Comment by denis-ivanov** [comment]
```html
<div class="hidden"><ac:structured-macro ac:name="section"> <ac:parameter ac:name="border">true</ac:parameter> ac:rich-text-body <ac:structured-macro ac:name="column"> <ac:parameter ac:name="width">100px</ac:parameter> ac:rich-text-body

    This is the content of column 1.
    
    </ac:rich-text-body> </ac:structured-macro> <ac:structured-macro ac:name="column"> ac:rich-text-body
    This is the content of column 2.
    
    </ac:rich-text-body> </ac:structured-macro> </ac:rich-text-body></ac:structured-macro>
```

This example is not correction html

**Comment by Morhpeuss** [comment]
> ```
> <div class="hidden"><ac:structured-macro ac:name="section"> <ac:parameter ac:name="border">true</ac:parameter> ac:rich-text-body <ac:structured-macro ac:name="column"> <ac:parameter ac:name="width">100px</ac:parameter> ac:rich-text-body
> 
>     This is the content of column 1.
>     
>     </ac:rich-text-body> </ac:structured-macro> <ac:structured-macro ac:name="column"> ac:rich-text-body
>     This is the content of column 2.
>     
>     </ac:rich-text-body> </ac:structured-macro> </ac:rich-text-body></ac:structured-macro>
> ```
> 
> This example is not corrected html

@denis-ivanov Yes, it is not the correct HTML, but it is the correct XML. As you can see, I am parsing the string with XML parse.  

I can remove the div tag and change the string like below, but the behavior is the same. I am not able to select all XML elements with a namespace.

xmlDoc.DocumentElement.SelectNodes(".//ac:structured-macro", xmlns, false) - *returns zero elements*

string xml = "<data><ac:structured-macro ac:name=\"section\">   <ac:parameter ac:name=\"border\">true</ac:parameter>  <ac:rich-text-body>    <ac:structured-macro ac:name=\"column\">      <ac:parameter ac:name=\"width\">100px</ac:parameter>      <ac:rich-text-body>        <p>This is the content of <strong>column 1</strong>.</p>      </ac:rich-text-body>    </ac:structured-macro>    <ac:structured-macro ac:name=\"column\">      <ac:rich-text-body>        <p>This is the content of <strong>column 2</strong>.</p>      </ac:rich-text-body>    </ac:structured-macro>  </ac:rich-text-body></ac:structured-macro></data>";

**Comment by denis-ivanov** [comment]
@Morhpeuss, could you provide full XHTML?
