### ISSUE TITLE
Xpath query support for Nodes?

### ISSUE THREAD

**Issue by fox112358** [AngleSharp/AngleSharp.XPath#45]
Hi, I migrated from HtmlAgilityPack to your library and want to run different XPath queries based on some data like I did with the old library. The issues is we need to run different queries on children nodes and therefore cannot combine all in one big XPath

```
           var parser = new HtmlParser();
           var doc = parser.ParseDocument(parserPreviewRequest.Body);

           var htmlBody = doc?.Body;

           INode headerContentBody = htmlBody?SelectSingleNode("some XPath");
           // some logic
           var test1 = headerContentBody?.SelectSingleNode("another xpath");
```

The last line of code is not correct since Node dose not contain definition for such method.
How can I achieve this? I cannot find any ability to run XPath queries on Nodes which is very strange.

Thanks!

**Comment by denis-ivanov** [comment]
Hi, @fox112358!
Please provide full HTML, XPath and expected result.

**Comment by fox112358** [comment]
Hi,

this is not about XPath, but ability to run XPath on INode

You see, we need to get some node by XPath, and based on some attributes
and other factors we compose another XPath query to run on its children
nodes

вт, 20 черв. 2023 р., 09:32 користувач Denis Ivanov <
***@***.***> пише:

**Comment by denis-ivanov** [comment]
You can cast your result to IElement and then again run XPath.

**Comment by fox112358** [comment]
Casting to IElement will not have any impact on XPath query result and will
not corrupt the results in any form, am I correct?

вт, 20 черв. 2023 р., 14:10 користувач Denis Ivanov <
***@***.***> пише:

**Comment by denis-ivanov** [comment]
It will not affect.
