### ISSUE TITLE
Tag <br/> is ignored

### ISSUE THREAD

**Issue by fox112358** [AngleSharp/AngleSharp.XPath#46]
```
<p
                    style="
                  margin-right: 0in;
                  margin-left: 0in;
                  font-size: 15px;
                  font-family: 'Arial', sans-serif;
                  line-height: 115%;
                ">
                    <h1>Heading 1</h1><br/><p>This is test line 1</p><p>This is test line 2</p><p>Body accepts HTML</p>
                </p>
```

In browser this looks like:

<p
                    style="
                  margin-right: 0in;
                  margin-left: 0in;
                  font-size: 15px;
                  font-family: 'Arial', sans-serif;
                  line-height: 115%;
                ">
                    <h1>Heading 1</h1><br/><p>This is test line 1</p><p>This is test line 2</p><p>Body accepts HTML</p>
                </p>

when I try to get text content from it like this

            ```
            var parser = new HtmlParser();
            var doc = parser.ParseDocument(data.Body);

            result = doc.Body?.TextContent;
```

I see in the output this: "Heading 1This is test line 1This is test line 2Body accepts HTML"

It ignores all new lines. Is there any other approach to get the text like it is parsed in browser?

**Comment by denis-ivanov** [comment]
@fox112358, please open new issue in AngleSharp/AngleSharp project.

**Comment by fox112358** [comment]
@denis-ivanov done
