### ISSUE TITLE
How to locate child node based on node?

### ISSUE THREAD

**Issue by CodingOctocat** [AngleSharp/AngleSharp.XPath#47]
If I use a Selector query then it returns `IElement` and I can continue to query for child elements relative to the result, but using `Body.SelectNodes("xpath")` returns the `INode` type, which `INode` cannot do.

```csharp
var recordNodes = document.Body.SelectNodes(TableRecordNodesXpath);

foreach (INode record in recordNodes)
{
    // record.SelectSingleNode("//relative to record"); // expected.
}
```

**Comment by denis-ivanov** [comment]
Hi, @CodingOctocat !
You can cast it to `IElement.`
